import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Copy, Mail, Trash2, XCircle, Plus } from "lucide-react";
import { format } from "date-fns";

interface Invite {
  id: string;
  invite_code: string;
  first_name: string;
  last_name: string;
  email: string;
  company: string | null;
  created_at: string;
  expires_at: string;
  used_at: string | null;
  is_active: boolean;
}

export function InviteManager() {
  const [invites, setInvites] = useState<Invite[]>([]);
  const [loading, setLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    company: "",
  });

  useEffect(() => {
    fetchInvites();
  }, []);

  const fetchInvites = async () => {
    try {
      const { data, error } = await supabase
        .from("invites")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      setInvites(data || []);
    } catch (error) {
      console.error("Error fetching invites:", error);
      toast.error("Failed to load invites");
    } finally {
      setLoading(false);
    }
  };

  const sendInviteEmail = async (invite: { firstName: string; lastName: string; email: string; inviteCode: string; company?: string }) => {
    try {
      const { error } = await supabase.functions.invoke("send-invite-email", {
        body: invite,
      });

      if (error) throw error;
      console.log("Invite email sent successfully");
    } catch (error) {
      console.error("Error sending invite email:", error);
      throw error;
    }
  };

  const handleCreateInvite = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      // Create invite in database
      // Note: invite_code will be auto-generated by the database trigger
      const { data: newInvite, error: insertError } = await supabase
        .from("invites")
        .insert([{
          first_name: formData.firstName,
          last_name: formData.lastName,
          email: formData.email,
          company: formData.company || null,
          created_by: user.id,
          invite_code: '', // Temporary value, will be replaced by trigger
        }])
        .select()
        .single();

      if (insertError) throw insertError;

      // Send invite email
      await sendInviteEmail({
        firstName: formData.firstName,
        lastName: formData.lastName,
        email: formData.email,
        inviteCode: newInvite.invite_code,
        company: formData.company || undefined,
      });

      toast.success("Invite created and email sent successfully!");
      setFormData({ firstName: "", lastName: "", email: "", company: "" });
      setIsDialogOpen(false);
      fetchInvites();
    } catch (error: any) {
      console.error("Error creating invite:", error);
      toast.error(error.message || "Failed to create invite");
    } finally {
      setLoading(false);
    }
  };

  const handleCopyLink = (inviteCode: string) => {
    const inviteUrl = `${window.location.origin}/#/signup?invite=${inviteCode}`;
    navigator.clipboard.writeText(inviteUrl);
    toast.success("Invite link copied to clipboard!");
  };

  const handleResendEmail = async (invite: Invite) => {
    try {
      await sendInviteEmail({
        firstName: invite.first_name,
        lastName: invite.last_name,
        email: invite.email,
        inviteCode: invite.invite_code,
        company: invite.company || undefined,
      });
      toast.success("Invite email resent successfully!");
    } catch (error) {
      toast.error("Failed to resend invite email");
    }
  };

  const handleRevoke = async (id: string) => {
    try {
      const { error } = await supabase
        .from("invites")
        .update({ is_active: false })
        .eq("id", id);

      if (error) throw error;
      toast.success("Invite revoked");
      fetchInvites();
    } catch (error) {
      toast.error("Failed to revoke invite");
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this invite?")) return;

    try {
      const { error } = await supabase.from("invites").delete().eq("id", id);
      if (error) throw error;
      toast.success("Invite deleted");
      fetchInvites();
    } catch (error) {
      toast.error("Failed to delete invite");
    }
  };

  const getStatus = (invite: Invite) => {
    if (!invite.is_active) return { label: "Revoked", variant: "destructive" as const };
    if (invite.used_at) return { label: "Used", variant: "default" as const };
    if (new Date(invite.expires_at) < new Date()) return { label: "Expired", variant: "secondary" as const };
    return { label: "Pending", variant: "outline" as const };
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle>Manage Invites</CardTitle>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="w-4 h-4 mr-2" />
              Create Invite
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Invite</DialogTitle>
              <DialogDescription>
                Send an invitation to join the platform. An email will be sent automatically.
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleCreateInvite} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="firstName">First Name *</Label>
                  <Input
                    id="firstName"
                    value={formData.firstName}
                    onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lastName">Last Name *</Label>
                  <Input
                    id="lastName"
                    value={formData.lastName}
                    onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                    required
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email Address *</Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="company">Company (Optional)</Label>
                <Input
                  id="company"
                  value={formData.company}
                  onChange={(e) => setFormData({ ...formData, company: e.target.value })}
                />
              </div>
              <div className="flex justify-end gap-2">
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={loading}>
                  {loading ? "Sending..." : "Send Invite"}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </CardHeader>
      <CardContent>
        {loading ? (
          <p className="text-center text-muted-foreground py-8">Loading invites...</p>
        ) : invites.length === 0 ? (
          <p className="text-center text-muted-foreground py-8">No invites yet. Create your first invite to get started.</p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Company</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Created</TableHead>
                <TableHead>Used</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {invites.map((invite) => {
                const status = getStatus(invite);
                return (
                  <TableRow key={invite.id}>
                    <TableCell className="font-medium">
                      {invite.first_name} {invite.last_name}
                    </TableCell>
                    <TableCell>{invite.email}</TableCell>
                    <TableCell>{invite.company || "-"}</TableCell>
                    <TableCell>
                      <Badge variant={status.variant}>{status.label}</Badge>
                    </TableCell>
                    <TableCell>{format(new Date(invite.created_at), "MMM d, yyyy")}</TableCell>
                    <TableCell>
                      {invite.used_at ? format(new Date(invite.used_at), "MMM d, yyyy") : "-"}
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleCopyLink(invite.invite_code)}
                          title="Copy invite link"
                        >
                          <Copy className="w-4 h-4" />
                        </Button>
                        {!invite.used_at && invite.is_active && (
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => handleResendEmail(invite)}
                            title="Resend email"
                          >
                            <Mail className="w-4 h-4" />
                          </Button>
                        )}
                        {!invite.used_at && invite.is_active && (
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => handleRevoke(invite.id)}
                            title="Revoke invite"
                          >
                            <XCircle className="w-4 h-4" />
                          </Button>
                        )}
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleDelete(invite.id)}
                          title="Delete invite"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  );
}
